// Code generated by protoc-gen-card-proto-plugin. DO NOT EDIT.

package proto

func (x *Action) WithCard(v *Action_SelectCard) *Action {
	x.Option = &Action_Card{
		Card: v,
	}
	return x
}
func (x *Action) WithXx(v int32) *Action {
	x.Option = &Action_Xx{
		Xx: v,
	}
	return x
}
func (x *Action) WithYy(v int32) *Action {
	x.Option = &Action_Yy{
		Yy: v,
	}
	return x
}
