// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: proto/action.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionType int32

const (
	ActionType_MAIN ActionType = 0
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "MAIN",
	}
	ActionType_value = map[string]int32{
		"MAIN": 0,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_action_proto_enumTypes[0].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_proto_action_proto_enumTypes[0]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_action_proto_rawDescGZIP(), []int{0}
}

type UserActionType int32

const (
	UserActionType_PRIMARY   UserActionType = 0
	UserActionType_SECONDARY UserActionType = 1
	UserActionType_FOCUS     UserActionType = 2
)

// Enum value maps for UserActionType.
var (
	UserActionType_name = map[int32]string{
		0: "PRIMARY",
		1: "SECONDARY",
		2: "FOCUS",
	}
	UserActionType_value = map[string]int32{
		"PRIMARY":   0,
		"SECONDARY": 1,
		"FOCUS":     2,
	}
)

func (x UserActionType) Enum() *UserActionType {
	p := new(UserActionType)
	*p = x
	return p
}

func (x UserActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_action_proto_enumTypes[1].Descriptor()
}

func (UserActionType) Type() protoreflect.EnumType {
	return &file_proto_action_proto_enumTypes[1]
}

func (x UserActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserActionType.Descriptor instead.
func (UserActionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_action_proto_rawDescGZIP(), []int{1}
}

type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Option:
	//
	//	*Action_Card
	//	*Action_Wait
	Option isAction_Option `protobuf_oneof:"option"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_action_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_proto_action_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_proto_action_proto_rawDescGZIP(), []int{0}
}

func (m *Action) GetOption() isAction_Option {
	if m != nil {
		return m.Option
	}
	return nil
}

func (x *Action) GetCard() *Action_SelectCard {
	if x, ok := x.GetOption().(*Action_Card); ok {
		return x.Card
	}
	return nil
}

func (x *Action) GetWait() *Action_WaitPlayer {
	if x, ok := x.GetOption().(*Action_Wait); ok {
		return x.Wait
	}
	return nil
}

type isAction_Option interface {
	isAction_Option()
}

type Action_Card struct {
	Card *Action_SelectCard `protobuf:"bytes,1,opt,name=card,proto3,oneof"`
}

type Action_Wait struct {
	Wait *Action_WaitPlayer `protobuf:"bytes,2,opt,name=wait,proto3,oneof"`
}

func (*Action_Card) isAction_Option() {}

func (*Action_Wait) isAction_Option() {}

type ActionResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type UserActionType `protobuf:"varint,2,opt,name=type,proto3,enum=proto.UserActionType" json:"type,omitempty"`
}

func (x *ActionResult) Reset() {
	*x = ActionResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_action_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResult) ProtoMessage() {}

func (x *ActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_action_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResult.ProtoReflect.Descriptor instead.
func (*ActionResult) Descriptor() ([]byte, []int) {
	return file_proto_action_proto_rawDescGZIP(), []int{1}
}

func (x *ActionResult) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ActionResult) GetType() UserActionType {
	if x != nil {
		return x.Type
	}
	return UserActionType_PRIMARY
}

type Notification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Notification string `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
}

func (x *Notification) Reset() {
	*x = Notification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_action_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_action_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_proto_action_proto_rawDescGZIP(), []int{2}
}

func (x *Notification) GetNotification() string {
	if x != nil {
		return x.Notification
	}
	return ""
}

type Action_ActionOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Selected    bool   `protobuf:"varint,5,opt,name=selected,proto3" json:"selected,omitempty"`
	Disabled    bool   `protobuf:"varint,6,opt,name=disabled,proto3" json:"disabled,omitempty"`
}

func (x *Action_ActionOption) Reset() {
	*x = Action_ActionOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_action_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action_ActionOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action_ActionOption) ProtoMessage() {}

func (x *Action_ActionOption) ProtoReflect() protoreflect.Message {
	mi := &file_proto_action_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action_ActionOption.ProtoReflect.Descriptor instead.
func (*Action_ActionOption) Descriptor() ([]byte, []int) {
	return file_proto_action_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Action_ActionOption) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Action_ActionOption) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Action_ActionOption) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Action_ActionOption) GetSelected() bool {
	if x != nil {
		return x.Selected
	}
	return false
}

func (x *Action_ActionOption) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type Action_SelectCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options []*Action_SelectCard_Option `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
}

func (x *Action_SelectCard) Reset() {
	*x = Action_SelectCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_action_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action_SelectCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action_SelectCard) ProtoMessage() {}

func (x *Action_SelectCard) ProtoReflect() protoreflect.Message {
	mi := &file_proto_action_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action_SelectCard.ProtoReflect.Descriptor instead.
func (*Action_SelectCard) Descriptor() ([]byte, []int) {
	return file_proto_action_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Action_SelectCard) GetOptions() []*Action_SelectCard_Option {
	if x != nil {
		return x.Options
	}
	return nil
}

type Action_WaitPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Action_WaitPlayer) Reset() {
	*x = Action_WaitPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_action_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action_WaitPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action_WaitPlayer) ProtoMessage() {}

func (x *Action_WaitPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_action_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action_WaitPlayer.ProtoReflect.Descriptor instead.
func (*Action_WaitPlayer) Descriptor() ([]byte, []int) {
	return file_proto_action_proto_rawDescGZIP(), []int{0, 2}
}

type Action_SelectCard_Option struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Option *Action_ActionOption `protobuf:"bytes,1,opt,name=option,proto3" json:"option,omitempty"`
	Card   *Card                `protobuf:"bytes,2,opt,name=card,proto3" json:"card,omitempty"`
}

func (x *Action_SelectCard_Option) Reset() {
	*x = Action_SelectCard_Option{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_action_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action_SelectCard_Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action_SelectCard_Option) ProtoMessage() {}

func (x *Action_SelectCard_Option) ProtoReflect() protoreflect.Message {
	mi := &file_proto_action_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action_SelectCard_Option.ProtoReflect.Descriptor instead.
func (*Action_SelectCard_Option) Descriptor() ([]byte, []int) {
	return file_proto_action_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *Action_SelectCard_Option) GetOption() *Action_ActionOption {
	if x != nil {
		return x.Option
	}
	return nil
}

func (x *Action_SelectCard_Option) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

var File_proto_action_proto protoreflect.FileDescriptor

var file_proto_action_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb8, 0x03,
	0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x43, 0x61, 0x72, 0x64,
	0x48, 0x00, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x12, 0x2e, 0x0a, 0x04, 0x77, 0x61, 0x69, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x57, 0x61, 0x69, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x48, 0x00, 0x52, 0x04, 0x77, 0x61, 0x69, 0x74, 0x1a, 0x8c, 0x01, 0x0a, 0x0c, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x1a, 0xa6, 0x01, 0x0a, 0x0a, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x39, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x43, 0x61, 0x72,
	0x64, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x1a, 0x5d, 0x0a, 0x06, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x32, 0x0a, 0x06, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1f, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64,
	0x1a, 0x0c, 0x0a, 0x0a, 0x57, 0x61, 0x69, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x08,
	0x0a, 0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x49, 0x0a, 0x0c, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x29, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x22, 0x32, 0x0a, 0x0c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2a, 0x16, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x41, 0x49, 0x4e, 0x10, 0x00, 0x2a,
	0x37, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x49, 0x4d, 0x41, 0x52, 0x59, 0x10, 0x00, 0x12, 0x0d,
	0x0a, 0x09, 0x53, 0x45, 0x43, 0x4f, 0x4e, 0x44, 0x41, 0x52, 0x59, 0x10, 0x01, 0x12, 0x09, 0x0a,
	0x05, 0x46, 0x4f, 0x43, 0x55, 0x53, 0x10, 0x02, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x68, 0x61, 0x6e, 0x61, 0x6e, 0x2f, 0x63, 0x61,
	0x72, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_action_proto_rawDescOnce sync.Once
	file_proto_action_proto_rawDescData = file_proto_action_proto_rawDesc
)

func file_proto_action_proto_rawDescGZIP() []byte {
	file_proto_action_proto_rawDescOnce.Do(func() {
		file_proto_action_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_action_proto_rawDescData)
	})
	return file_proto_action_proto_rawDescData
}

var file_proto_action_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_action_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_action_proto_goTypes = []interface{}{
	(ActionType)(0),                  // 0: proto.ActionType
	(UserActionType)(0),              // 1: proto.UserActionType
	(*Action)(nil),                   // 2: proto.Action
	(*ActionResult)(nil),             // 3: proto.ActionResult
	(*Notification)(nil),             // 4: proto.Notification
	(*Action_ActionOption)(nil),      // 5: proto.Action.ActionOption
	(*Action_SelectCard)(nil),        // 6: proto.Action.SelectCard
	(*Action_WaitPlayer)(nil),        // 7: proto.Action.WaitPlayer
	(*Action_SelectCard_Option)(nil), // 8: proto.Action.SelectCard.Option
	(*Card)(nil),                     // 9: proto.Card
}
var file_proto_action_proto_depIdxs = []int32{
	6, // 0: proto.Action.card:type_name -> proto.Action.SelectCard
	7, // 1: proto.Action.wait:type_name -> proto.Action.WaitPlayer
	1, // 2: proto.ActionResult.type:type_name -> proto.UserActionType
	8, // 3: proto.Action.SelectCard.options:type_name -> proto.Action.SelectCard.Option
	5, // 4: proto.Action.SelectCard.Option.option:type_name -> proto.Action.ActionOption
	9, // 5: proto.Action.SelectCard.Option.card:type_name -> proto.Card
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_action_proto_init() }
func file_proto_action_proto_init() {
	if File_proto_action_proto != nil {
		return
	}
	file_proto_card_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_action_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_action_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_action_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Notification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_action_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action_ActionOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_action_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action_SelectCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_action_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action_WaitPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_action_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action_SelectCard_Option); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_action_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Action_Card)(nil),
		(*Action_Wait)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_action_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_action_proto_goTypes,
		DependencyIndexes: file_proto_action_proto_depIdxs,
		EnumInfos:         file_proto_action_proto_enumTypes,
		MessageInfos:      file_proto_action_proto_msgTypes,
	}.Build()
	File_proto_action_proto = out.File
	file_proto_action_proto_rawDesc = nil
	file_proto_action_proto_goTypes = nil
	file_proto_action_proto_depIdxs = nil
}
