// Code generated by protoc-gen-card-proto-plugin. DO NOT EDIT.

package proto

func (x *Action) WithCard(v *Action_SelectCard) *Action {
	x.Option = &Action_Card{
		Card: v,
	}
	return x
}
func (x *Action) WithWait(v *Action_WaitPlayer) *Action {
	x.Option = &Action_Wait{
		Wait: v,
	}
	return x
}
