// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: proto/plugin_methods.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPluginInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPluginInfo) Reset() {
	*x = GetPluginInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_plugin_methods_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginInfo) ProtoMessage() {}

func (x *GetPluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_methods_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginInfo.ProtoReflect.Descriptor instead.
func (*GetPluginInfo) Descriptor() ([]byte, []int) {
	return file_proto_plugin_methods_proto_rawDescGZIP(), []int{0}
}

type StartGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartGame) Reset() {
	*x = StartGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_plugin_methods_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGame) ProtoMessage() {}

func (x *StartGame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_methods_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGame.ProtoReflect.Descriptor instead.
func (*StartGame) Descriptor() ([]byte, []int) {
	return file_proto_plugin_methods_proto_rawDescGZIP(), []int{1}
}

type GetPluginInfo_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPluginInfo_Req) Reset() {
	*x = GetPluginInfo_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_plugin_methods_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPluginInfo_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginInfo_Req) ProtoMessage() {}

func (x *GetPluginInfo_Req) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_methods_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginInfo_Req.ProtoReflect.Descriptor instead.
func (*GetPluginInfo_Req) Descriptor() ([]byte, []int) {
	return file_proto_plugin_methods_proto_rawDescGZIP(), []int{0, 0}
}

type GetPluginInfo_Resp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *PluginInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *GetPluginInfo_Resp) Reset() {
	*x = GetPluginInfo_Resp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_plugin_methods_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPluginInfo_Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginInfo_Resp) ProtoMessage() {}

func (x *GetPluginInfo_Resp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_methods_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginInfo_Resp.ProtoReflect.Descriptor instead.
func (*GetPluginInfo_Resp) Descriptor() ([]byte, []int) {
	return file_proto_plugin_methods_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GetPluginInfo_Resp) GetInfo() *PluginInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type StartGame_Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Seed uint64 `protobuf:"varint,2,opt,name=seed,proto3" json:"seed,omitempty"`
}

func (x *StartGame_Req) Reset() {
	*x = StartGame_Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_plugin_methods_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartGame_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGame_Req) ProtoMessage() {}

func (x *StartGame_Req) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_methods_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGame_Req.ProtoReflect.Descriptor instead.
func (*StartGame_Req) Descriptor() ([]byte, []int) {
	return file_proto_plugin_methods_proto_rawDescGZIP(), []int{1, 0}
}

func (x *StartGame_Req) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StartGame_Req) GetSeed() uint64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

type StartGame_Resp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartGame_Resp) Reset() {
	*x = StartGame_Resp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_plugin_methods_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartGame_Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGame_Resp) ProtoMessage() {}

func (x *StartGame_Resp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_methods_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGame_Resp.ProtoReflect.Descriptor instead.
func (*StartGame_Resp) Descriptor() ([]byte, []int) {
	return file_proto_plugin_methods_proto_rawDescGZIP(), []int{1, 1}
}

var File_proto_plugin_methods_proto protoreflect.FileDescriptor

var file_proto_plugin_methods_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x6d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x50, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x05, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x1a,
	0x2d, 0x0a, 0x04, 0x52, 0x65, 0x73, 0x70, 0x12, 0x25, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x42,
	0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x1a, 0x2d, 0x0a, 0x03, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x65, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x65, 0x65, 0x64, 0x1a, 0x06, 0x0a, 0x04, 0x52, 0x65,
	0x73, 0x70, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6f, 0x68, 0x61, 0x6e, 0x61, 0x6e, 0x2f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_plugin_methods_proto_rawDescOnce sync.Once
	file_proto_plugin_methods_proto_rawDescData = file_proto_plugin_methods_proto_rawDesc
)

func file_proto_plugin_methods_proto_rawDescGZIP() []byte {
	file_proto_plugin_methods_proto_rawDescOnce.Do(func() {
		file_proto_plugin_methods_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_plugin_methods_proto_rawDescData)
	})
	return file_proto_plugin_methods_proto_rawDescData
}

var file_proto_plugin_methods_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_plugin_methods_proto_goTypes = []interface{}{
	(*GetPluginInfo)(nil),      // 0: proto.GetPluginInfo
	(*StartGame)(nil),          // 1: proto.StartGame
	(*GetPluginInfo_Req)(nil),  // 2: proto.GetPluginInfo.Req
	(*GetPluginInfo_Resp)(nil), // 3: proto.GetPluginInfo.Resp
	(*StartGame_Req)(nil),      // 4: proto.StartGame.Req
	(*StartGame_Resp)(nil),     // 5: proto.StartGame.Resp
	(*PluginInfo)(nil),         // 6: proto.PluginInfo
}
var file_proto_plugin_methods_proto_depIdxs = []int32{
	6, // 0: proto.GetPluginInfo.Resp.info:type_name -> proto.PluginInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_plugin_methods_proto_init() }
func file_proto_plugin_methods_proto_init() {
	if File_proto_plugin_methods_proto != nil {
		return
	}
	file_proto_plugin_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_plugin_methods_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPluginInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_plugin_methods_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_plugin_methods_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPluginInfo_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_plugin_methods_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPluginInfo_Resp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_plugin_methods_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartGame_Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_plugin_methods_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartGame_Resp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_plugin_methods_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_plugin_methods_proto_goTypes,
		DependencyIndexes: file_proto_plugin_methods_proto_depIdxs,
		MessageInfos:      file_proto_plugin_methods_proto_msgTypes,
	}.Build()
	File_proto_plugin_methods_proto = out.File
	file_proto_plugin_methods_proto_rawDesc = nil
	file_proto_plugin_methods_proto_goTypes = nil
	file_proto_plugin_methods_proto_depIdxs = nil
}
